package types

type Host struct {
	ID                                string      `json:"id"`
	IP                                string      `json:"ip"`
	SwitchUplinkPortDto               interface{} `json:"switchUplinkPortDto"`
	UplinkTopoDto                     interface{} `json:"uplinkTopoDto"`
	Pnics                             interface{} `json:"pnics"`
	Disks                             interface{} `json:"disks"`
	Name                              string      `json:"name"`
	HostName                          string      `json:"hostName"`
	NodeVersion                       string      `json:"nodeVersion"`
	DisplayNodeVersion                string      `json:"displayNodeVersion"`
	DisplayHotfixVersion              string      `json:"displayHotfixVersion"`
	Password                          string      `json:"password"`
	DataCenterID                      string      `json:"dataCenterId"`
	DataCenterName                    string      `json:"dataCenterName"`
	ClusterName                       string      `json:"clusterName"`
	ClusterID                         string      `json:"clusterId"`
	Status                            string      `json:"status"`
	CPUSocket                         int         `json:"cpuSocket"`
	CPUCorePerSocket                  int         `json:"cpuCorePerSocket"`
	CPUThreadPerCore                  int         `json:"cpuThreadPerCore"`
	LogicCPUNum                       int         `json:"logicCpuNum"`
	LogicalProcessor                  int         `json:"logicalProcessor"`
	CPUFrequency                      float64     `json:"cpuFrequency"`
	CPUUsage                          float64     `json:"cpuUsage"`
	CPUTotalHz                        float64     `json:"cpuTotalHz"`
	FreeCPU                           float64     `json:"freeCpu"`
	UsedCPU                           float64     `json:"usedCpu"`
	TotalMem                          float64     `json:"totalMem"`
	LogicTotalMem                     float64     `json:"logicTotalMem"`
	TotalMemInByte                    int         `json:"totalMemInByte,omitempty"`
	LogicTotalMemInByte               int         `json:"logicTotalMemInByte,omitempty"`
	MemoryUsage                       float64     `json:"memoryUsage"`
	FreeMemory                        float64     `json:"freeMemory"`
	UsedMemory                        float64     `json:"usedMemory"`
	FreeMemoryInByte                  int         `json:"freeMemoryInByte,omitempty"`
	UsedMemoryInByte                  int         `json:"usedMemoryInByte,omitempty"`
	LogicUsedMemory                   float64     `json:"logicUsedMemory"`
	LogicFreeMemory                   float64     `json:"logicFreeMemory"`
	LogicUsedMemoryInByte             int         `json:"logicUsedMemoryInByte"`
	LogicFreeMemoryInByte             int         `json:"logicFreeMemoryInByte,omitempty"`
	PnicNum                           int         `json:"pnicNum"`
	NormalRunTime                     float64     `json:"normalRunTime"`
	Model                             string      `json:"model"`
	CPUType                           string      `json:"cpuType"`
	VtDegree                          float64     `json:"vtDegree"`
	PowerState                        string      `json:"powerstate"`
	HostBmcDto                        interface{} `json:"hostBmcDto"`
	Tags                              []Tag       `json:"tags"`
	MountPath                         string      `json:"mountPath"`
	MonMountState                     string      `json:"monMountState"`
	CPUModel                          []string    `json:"cpuModel"`
	NetworkDtos                       interface{} `json:"networkDtos"`
	PortIP                            string      `json:"portIp"`
	Monstatus                         bool        `json:"monstatus"`
	HostIqn                           string      `json:"hostIqn"`
	VxlanPortDto                      interface{} `json:"vxlanPortDto"`
	SdnUpLinks                        interface{} `json:"sdnUpLinks"`
	AllPNicsCount                     int         `json:"allPNicsCount"`
	AvailablePNicsCount               int         `json:"availablePNicsCount"`
	CfsDomainStatus                   string      `json:"cfsDomainStatus"`
	SerialNumber                      string      `json:"serialNumber"`
	Manufacturer                      string      `json:"manufacturer"`
	IndicatorStatus                   string      `json:"indicatorStatus"`
	EntryTemperature                  string      `json:"entryTemperature"`
	MulticastEnabled                  bool        `json:"multicastEnabled"`
	BroadcastLimitEnabled             bool        `json:"broadcastLimitEnabled"`
	Pcies                             interface{} `json:"pcies"`
	VgpuEnable                        bool        `json:"vgpuEnable"`
	SpecialFailover                   bool        `json:"specialFailover"`
	VswitchDtos                       interface{} `json:"vswitchDtos"`
	HotfixVersion                     string      `json:"hotfixVersion"`
	VmMigBandWidth                    string      `json:"vmMigBandWidth"`
	VmMigBandWidthFlag                bool        `json:"vmMigBandWidthFlag"`
	DpdkEnabled                       bool        `json:"dpdkEnabled"`
	HugePageTotal                     float64     `json:"hugePageTotal"`
	HugePageUsed                      float64     `json:"hugePageUsed"`
	HugePageFree                      float64     `json:"hugePageFree"`
	HugePageTotalInByte               int         `json:"hugePageTotalInByte,omitempty"`
	HugePageUsedInByte                int         `json:"hugePageUsedInByte"`
	HugePageFreeInByte                int         `json:"hugePageFreeInByte",omitempty`
	StorageUsage                      float64     `json:"storageUsage"`
	NodeForm                          string      `json:"nodeForm"`
	CpuArchType                       string      `json:"cpuArchType"`
	CpuVendor                         string      `json:"cpuVendor"`
	LogPartitionSize                  int         `json:"logPartitionSize"`
	RootPartitionSize                 int         `json:"rootPartitionSize"`
	Cpuflags                          string      `json:"cpuflags"`
	AllocatedVcpuNum                  int         `json:"allocatedVcpuNum"`
	AllocatedMemory                   int         `json:"allocatedMemory"`
	AllocatedMemoryInByte             int         `json:"allocatedMemoryInByte"`
	KmsConfigured                     bool        `json:"kmsConfigured"`
	Datastores                        interface{} `json:"datastores"`
	ScvmAllowed                       bool        `json:"scvmAllowed"`
	UsedVCpus                         int         `json:"usedVCpus"`
	ContainerStatus                   string      `json:"containerStatus"`
	AntivirusStatus                   string      `json:"antivirusStatus"`
	TotalLocalDatastoreCapacityInByte int         `json:"totalLocalDatastoreCapacityInByte"`
	UsedLocalDatastoreCapacityInByte  int         `json:"usedLocalDatastoreCapacityInByte"`
	LocalDataStoreUsage               float64     `json:"localDataStoreUsage"`
	LocalDataStoreMultiplexRatio      float64     `json:"localDataStoreMultiplexRatio"`
	UPS                               interface{} `json:"ups"`
	SdsDomainId                       string      `json:"sdsDomainId,omitempty"`
	HostTotalMemInMB                  float64     `json:"hostTotalMemInMB,omitempty"`
	HostTotalMemInByte                int         `json:"hostTotalMemInByte"`
	CpuTotalRatio                     float64     `json:"cpuTotalRatio,omitempty"`
	MemTotalRatio                     float64     `json:"memTotalRatio,omitempty"`
	HugePageEnabled                   bool        `json:"hugePageEnabled,omitempty"`
	HugePageActived                   bool        `json:"hugePageActived,omitempty"`
	TotalDataStoreCapacityInByte      int         `json:"totalDataStoreCapacityInByte"`
	UsedDataStoreCapacityInByte       int         `json:"usedDataStoreCapacityInByte"`
	DataStoreUsage                    float64     `json:"dataStoreUsage"`
}

type HostPageResponse struct {
	TotalPage   int    `json:"totalPage"`
	CurrentPage int    `json:"currentPage"`
	TotalSize   int    `json:"totalSize"`
	Items       []Host `json:"items"`
}

type HostHealthInfo struct {
	ID           string  `json:"id"`
	IP           string  `json:"ip"`
	Score        float64 `json:"score"`
	CpuScore     float64 `json:"cpuScore"`
	CpuPerf      float64 `json:"cpuPerf"`
	CpuUsed      float64 `json:"cpuUsed"`
	CpuTotal     float64 `json:"cpuTotal"`
	MemScore     float64 `json:"memScore"`
	MemPerf      float64 `json:"memPerf"`
	MemUsed      float64 `json:"memUsed"`
	MemTotal     float64 `json:"memTotal"`
	StorageScore float64 `json:"storageScore"`
	StoragePerf  float64 `json:"storagePerf"`
	StorageUsed  float64 `json:"storageUsed"`
	StorageTotal float64 `json:"storageTotal"`
	NetworkScore float64 `json:"networkScore"`
	NetworkPerf  float64 `json:"networkPerf"`
	NetworkUsed  float64 `json:"networkUsed"`
	NetworkTotal float64 `json:"networkTotal"`
}
